# permissions for end users to view mariadbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbcluster-viewer-role
rules:
- apiGroups:
  - mariadb.mariadb-galera-cluster-operator.domain
  resources:
  - mariadbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mariadb.mariadb-galera-cluster-operator.domain
  resources:
  - mariadbclusters/status
  verbs:
  - get
