apiVersion: v1
kind: Service
metadata:
  name: mariadb-test
  labels:
    app: mariadb-test
spec:
  ports:
    - name: mariadb-test
      port: 3306
  clusterIP: None
  selector:
    app: mariadb-test