apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-test
spec:
  selector:
    matchLabels:
      app: mariadb-test
  serviceName: mariadb-test
  replicas: 2
  template:
    metadata:
      labels:
        app: mariadb-test
    spec:
      initContainers:
        - name: init-mariadb-test
          image: mariadb:10.3.10
          command:
            - bash
            - "-c"
            - |
              set -ex
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              echo [mysqld] > /mnt/conf.d/MariaDBCluster.cnf
              echo binlog_format=ROW >> /mnt/conf.d/MariaDBCluster.cnf
              echo default-storage-engine=innodb >> /mnt/conf.d/MariaDBCluster.cnf
              echo innodb_autoinc_lock_mode=2 >> /mnt/conf.d/MariaDBCluster.cnf
              echo bind-address=0.0.0.0 >> /mnt/conf.d/MariaDBCluster.cnf
              echo [galera] >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_provider=/usr/lib/galera/libgalera_smm.so >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_cluster_name='Galera_Cluster' >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_slave_threads = 8 >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_log_conflicts=1 >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_on=ON >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_provider_options='gcache.size=2G' >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_forced_binlog_format=ROW >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_drupal_282555_workaround=1 >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_max_ws_size=2147483647 >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_sst_method=rsync >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_sst_auth=galera:galera >> /mnt/conf.d/MariaDBCluster.cnf
              echo query_cache_size=0 >> /mnt/conf.d/MariaDBCluster.cnf
              echo default_storage_engine=InnoDB >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_cluster_address='gcomm://mariadb-test-0,mariadb-test-1,mariadb-test-2' >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_node_address=mariadb-test-${ordinal} >> /mnt/conf.d/MariaDBCluster.cnf
              echo wsrep_node_name=MariaDB-Node-${ordinal} >> /mnt/conf.d/MariaDBCluster.cnf
              if [[ $ordinal -eq 0 ]]; then
                echo "docker-entrypoint.sh mysqld --user=root --wsrep-new-cluster" > /mnt/start-fzx/start-up.sh
              else
                echo "docker-entrypoint.sh mysqld --user=root" > /mnt/start-fzx/start-up.sh
              fi
              chmod 777 /mnt/start-fzx/start-up.sh
          volumeMounts:
            - name: conf
              mountPath: /mnt/conf.d
            - name: start-up
              mountPath: /mnt/start-fzx
      containers:
        - name: mariadb
          image: mariadb:10.3.10
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          command:
            - bash
            - "-c"
            - "/etc/mysql/start-fzx/start-up.sh"
          ports:
            - name: mysql
              containerPort: 3306
            - name: communication
              containerPort: 4567
            - name: ist
              containerPort: 4568
            - name: sst
              containerPort: 4444
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: mysql
            - name: conf
              mountPath: /etc/mysql/conf.d
            - name: start-up
              mountPath: /etc/mysql/start-fzx
      volumes:
        - name: conf
          hostPath:
            path: "/root/k8s/test-config"
            type: Directory
        - name: start-up
          hostPath:
            path: "/root/k8s/test-config"
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: "nginx-nfs-storage"  #存储类名，改为集群中已存在的
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi